// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	profile "bookstore/user/internal/handler/profile"
	user "bookstore/user/internal/handler/user"
	"bookstore/user/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/api/user/:name",
			Handler: user.GetUserHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/users/create",
			Handler: user.CreateUserHandler(serverCtx),
		},
	})

	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/api/profile/:name",
			Handler: profile.GetProfileHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/api/profile/create",
			Handler: profile.CreateProfileHandler(serverCtx),
		},
	}, rest.WithJwt(serverCtx.Config.Auth.AccessSecret))

	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodHead,
			Path:    "/api/ping",
			Handler: pingHandler(serverCtx),
		},
	})
}
