// Code generated by goctl. DO NOT EDIT.
package types

type Address struct {
	City string `json:"city"`
}

type CreateRequest struct {
	InnerType
	Name    string    `form:"name"`
	Age     Int       `form:"age,optional"`
	Address []Address `json:"address,optional"`
}

type GetRequest struct {
	Name string `path:"name"`
	Age  Int    `form:"age,optional"`
}

type GetResponse struct {
	Code    Int     `json:"code"`
	Desc    string  `json:"desc,omitempty"`
	Address Address `json:"address"`
	Service Int     `json:"service"`
}

type InnerType struct {
	Image string `json:"image"`
}

type Int struct {
}

type Student struct {
	Name string `json:"name"` // 学生姓名
}

type Teacher struct {
}

type User struct {
	Name string `json:"name"` // 用户姓名
}
